version: 1
builder:
  configs:
    - documentation_targets:
        - DynamoQueries
        - DynamoQueriesSoto
        - DynamoQueriesTestSupport
        - DynamoQueriesSnapshotTesting
        - Routing
        - APIGatewayV2Server
