import Foundation

/// The DynamoDB scalar type of a key attribute.
///
/// `CreateTable`'s `AttributeDefinitions` only admit these three; non-scalar
/// encodings (`BOOL`, `L`, `M`, sets) can't participate in a key schema.
public enum DynamoKeyType: String, Sendable {
    case string = "S"
    case number = "N"
    case binary = "B"
}

/// One attribute of a table or index key: the on-the-wire attribute name plus
/// the scalar type DynamoDB requires up front in `AttributeDefinitions`.
///
/// Generated by the ``Table(_:)`` macro, which resolves each declared key
/// against the property it names and reads the type off the property's
/// ``DynamoKeyEncodable`` conformance.
public struct KeyAttribute: Sendable, Equatable {
    public let name: String
    public let type: DynamoKeyType

    public init(_ name: String, type: DynamoKeyType) {
        self.name = name
        self.type = type
    }
}

/// Types whose ``DynamoEncodable`` encoding is a key-legal scalar (`S`, `N`,
/// or `B`). The ``Table(_:)`` macro emits `(PropertyType).dynamoKeyType` for
/// every declared key, so a type works as a key only if it conforms.
///
/// `Bool` deliberately has no conformance: it encodes as `BOOL`, which
/// DynamoDB rejects in key schemas. Store key-participating flags as `Int`.
public protocol DynamoKeyEncodable {
    static var dynamoKeyType: DynamoKeyType { get }
}

extension String: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { .string }
}

extension UUID: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { .string }
}

extension URL: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { .string }
}

extension Int: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { .number }
}

extension Double: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { .number }
}

/// `Date` encodes as epoch-seconds in a Number (see the `DynamoEncodable`
/// conformance in `Core/DynamoValue.swift`), so its key type is `N`.
extension Date: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { .number }
}

extension Data: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { .binary }
}

/// Raw-representable enums key on their raw value's scalar type. As with
/// `DynamoEncodable`, the conformance is opt-in:
/// `extension Status: DynamoKeyEncodable {}`.
extension DynamoKeyEncodable where Self: RawRepresentable, RawValue: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { RawValue.dynamoKeyType }
}

/// Optional key properties are legal and produce a *sparse* index: items
/// missing any key attribute don't appear in it.
extension Optional: DynamoKeyEncodable where Wrapped: DynamoKeyEncodable {
    public static var dynamoKeyType: DynamoKeyType { Wrapped.dynamoKeyType }
}
