/// Runtime description of a table's primary-key shape.
///
/// Generated by the ``Table(_:)`` macro and exposed on every model as the
/// static `_table` property required by ``DynamoModel``. Operation builders
/// read it to decide which primary-key arity to demand, and to fail fast
/// with ``PrimaryKeyError`` when a call site uses the wrong overload.
public struct TableMetadata: Sendable {
    /// On-the-wire DynamoDB table name.
    public let name: String

    /// The partition (hash) key.
    public let partitionKey: KeyAttribute

    /// The sort (range) key, or `nil` for partition-only tables.
    public let sortKey: KeyAttribute?

    public init(name: String, partitionKey: KeyAttribute, sortKey: KeyAttribute? = nil) {
        self.name = name
        self.partitionKey = partitionKey
        self.sortKey = sortKey
    }
}
